Ritmus/Ritmus.ShoppingCart.MvcWebUI/Models/CartLineAddViewModel.cs
using Ritmus.ShoppingCart.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ritmus.ShoppingCart.MvcWebUI.Models
{
    public class CartLineAddViewModel
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Models/CartSummaryViewModel.cs
using Ritmus.ShoppingCart.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ritmus.ShoppingCart.MvcWebUI.Models
{
    public class CartSummaryViewModel
    {
        public Cart Cart { get; set; }
    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Models/CategoryListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ritmus.ShoppingCart.Entities.Concrete;

namespace Ritmus.ShoppingCart.MvcWebUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; internal set; }
        public int CurrentCategory { get; internal set; }
    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Models/ProductListViewModel.cs
using Ritmus.ShoppingCart.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ritmus.ShoppingCart.MvcWebUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; internal set; }
        public int PageCount { get; internal set; }
        public int PageSize { get; internal set; }
        public int CurrentCategory { get; internal set; }
        public int CurrentPage { get; internal set; }
    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Ritmus.ShoppingCart.BLL.Abstract;
using Ritmus.ShoppingCart.Entities.Concrete;
using Ritmus.ShoppingCart.MvcWebUI.Models;
using Ritmus.ShoppingCart.MvcWebUI.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ritmus.ShoppingCart.MvcWebUI.Controllers
{
    public class CartController:Controller
    {
        private ICartSessionService _cartSessionService;
        private ICartService _cartService;
        private IProductService _productService;

        public CartController(
            ICartSessionService cartSessionService,
            ICartService cartService,
            IProductService productService)
        {
            _cartSessionService = cartSessionService;
            _cartService = cartService;
            _productService = productService;
        }

        public ActionResult AddToCart(int productId)
        {
            var productToBeAdded = _productService.GetById(productId);
            var cart = _cartSessionService.GetCart();
            _cartService.AddToCart(cart, productToBeAdded);
            _cartSessionService.SetCart(cart);

            TempData.Add("message", String.Format("{0},Başarıyla Sepete Eklendi!", productToBeAdded.ProductName));
           

            return RedirectToAction("Index", "Product");
        }       

        public ActionResult Remove(int productId)
        {
            var cart = _cartSessionService.GetCart();
            _cartService.RemoveFromCart(cart, productId);
            _cartSessionService.SetCart(cart);
            TempData.Add("message", String.Format("Ürün Sepetten Başarıyla Silindi"));
            return RedirectToAction("Index","Product");
        }

    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Ritmus.ShoppingCart.BLL.Abstract;
using Ritmus.ShoppingCart.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ritmus.ShoppingCart.MvcWebUI.Controllers
{
    public class ProductController:Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public ActionResult Index(int page = 1, int category=0)
        {
            int pageSize = 6;
            var products = _productService.GetByCategory(category);
            ProductListViewModel model = new ProductListViewModel
            {
                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount = (int)Math.Ceiling(products.Count / (double)pageSize), //yukarı yuvarlama
                PageSize = pageSize,
                CurrentCategory = category,
                CurrentPage = page
            };

            return View(model);
        }
    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/ViewComponents/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Ritmus.ShoppingCart.MvcWebUI.Models;
using Ritmus.ShoppingCart.MvcWebUI.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ritmus.ShoppingCart.MvcWebUI.ViewComponents
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private ICartSessionService _cartSessionService;

        public CartSummaryViewComponent(ICartSessionService cartSessionService)
        {
            _cartSessionService = cartSessionService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CartSummaryViewModel
            {
                Cart = _cartSessionService.GetCart()
            };
            return View(model);
        }
    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Ritmus.ShoppingCart.BLL.Abstract;
using Ritmus.ShoppingCart.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ritmus.ShoppingCart.MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory=Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Views/Product/Index.cshtml
@model Ritmus.ShoppingCart.MvcWebUI.Models.ProductListViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="row">
        @foreach (var product in Model.Products)
        {
            <div class="col-md-4">
                <figure class="card card-product">
                    <div class="img-wrap">
                        <img src="~/images/@product.Image" />
                    </div>
                    <figcaption class="info-wrap">
                        <h4 class="title">@product.ProductName</h4>
                        <div class="price-wrap h5">
                            <span class="price-new">@product.UnitPrice TL</span>
                        </div> <!-- price-wrap.// -->
                        <a class="btn btn-xs btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@product.ProductId">Sepete Ekle</a>
                    </figcaption>

                </figure>
            </div> <!-- col // -->
        }
    </div> <!-- row.// -->

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Views/Shared/Components/CartSummary/Default.cshtml
@model Ritmus.ShoppingCart.MvcWebUI.Models.CartSummaryViewModel

<div class="col-md-6">
    <table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:40%">Ürün</th>
                <th style="width:18%">Fiyat</th>
                <th style="width:22%" class="text-center">Adet</th>
                <th style="width:10%"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cart.CartLines)
            {
                <tr>
                    <td data-th="Product">
                        <div class="row">
                            <div class="col-sm-10">
                                <h4 class="nomargin">@item.Product.ProductName</h4>
                            </div>
                        </div>
                    </td>
                    <td data-th="Price">Toplam: @item.Product.UnitPrice TL</td>
                    <td data-th="Quantity">
                        <input type="number" class="form-control text-center" disabled value="@item.Quantity">
                    </td>
                    <td class="actions" data-th="">

                        <a class="btn btn-xs btn-danger" asp-controller="Cart" asp-action="Remove" asp-route-productId="@item.Product.ProductId"><span class="glyphicon glyphicon-remove"></span> Sil</a>
                    </td>
                </tr>
            }

        </tbody>
        <tfoot>
            <tr class="visible-xs">
                <td class="text-center"><strong></strong></td>
            </tr>
            <tr>
                <td colspan="2" class="hidden-xs"></td>
                <td class="hidden-xs text-center"><strong>@Model.Cart.Total TL</strong></td>
            </tr>
        </tfoot>
    </table>
</div>

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Views/Shared/Components/CategoryList/default.cshtml
@model Ritmus.ShoppingCart.MvcWebUI.Models.CategoryListViewModel

@foreach (var category in Model.Categories)
{
    var css = "";
    if (category.CategoryId == Model.CurrentCategory)
    {
        css += " active";
    }

    <li class="@css">
        <a href="/product/index?category=@category.CategoryId">@category.CategoryName</a>
    </li>
}

<br />

Ritmus/Ritmus.ShoppingCart.MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <style>
        /*Ürün style*/
        .card-product .img-wrap {
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 150px;
            text-align: center;
        }

            .card-product .img-wrap img {
                max-height: 100%;
                max-width: 100%;
                object-fit: cover;
            }

        .card-product .info-wrap {
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
            text-align: center;
        }

        .card-product .bottom-wrap {
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .label-rating {
            margin-right: 10px;
            color: #333;
            display: inline-block;
            vertical-align: middle;
        }

        .card-product .price-old {
            color: #999;
        }
    </style>
    <div class="col-md-12">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/Product/Index">Anasayfa</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    
                    <ul class="nav navbar-nav">
                        @await Component.InvokeAsync("CategoryList")
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success" role="alert">@TempData["message"]</div>
        }
    </div>

    <div class="col-md-6">

        @RenderBody()
    </div>
    @await Component.InvokeAsync("CartSummary")
    <div class="col-md-12">
        <footer class="footer">
            <div class="container">
                <p class="text-center">Copyright @DateTime.Now.Year | Designed by <a href="https://www.linkedin.com/in/mertcanaksoy">Mert AKSOY</a> for Ritmus</p>               
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </div>

</body>

</html>